services:
  mariadb:
    image: yobasystems/alpine-mariadb
    container_name: mariadb_container
    restart: unless-stopped
    env_file:
      - ../../.env
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER --password=$MYSQL_PASSWORD || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 1
      start_period: 30s
  volumes:
      - mariadb_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge

volumes:
  mariadb_data: